[build]
  command = "npm run build"
  publish="https://github.com/Lydiadev77/Superhero/tree/master/superheroes_ant/build"
  base = "https://github.com/Lydiadev77/Superhero/tree/master/superheroes_ant"

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200